PaymentGatewayIntegration/Controllers/BlockchainController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PaymentGatewayIntegration.Models;
using PaymentGatewayIntegration.Services;

namespace PaymentGatewayIntegration.Controllers
{
	public class BlockchainController : Controller
	{
		private readonly IBlockChainService _blockChainService;
		public BlockchainController(IBlockChainService blockChainService)
		{
			_blockChainService = blockChainService;
		}

		public async Task<IActionResult> Index()
		{
			var model = new BlockchainModel();
			var response = await _blockChainService.GetBTCValue();
			if(response != null)
			{
				model.MarketPriceUsd = response.MarketPriceUsd;
			}
			return View(model);
		}

		public async Task<IActionResult> ProcessPayment()
		{
			var response = await _blockChainService.ProccessPayment();
			return View(response);
		}

		public string Success()
		{
			var queryParams = HttpContext.Request.Query;
			foreach (var item in queryParams)
			{
				Console.WriteLine(item.Key + " " + item.Value);
			}

			//var invoice_id = HttpContext.Request.Query["invoice_id"];
			//var transaction_hash = HttpContext.Request.Query["transaction_hash"];
			//var value = HttpContext.Request.Query["value"];
			//var address = HttpContext.Request.Query["address"];
			//var secret = HttpContext.Request.Query["secret"];
			//var confirmations = HttpContext.Request.Query["confirmations"];
			var status = "*ok*";
			//if(confirmations > 4)
			return status;
		}

		[Route("Blockchain/AddressDetails/{address}")]
		public async Task<IActionResult> AddressDetails(string address)
        {
			var response = await _blockChainService.GetAddressDetails(address);
			return View(response);
		}
	}
}

PaymentGatewayIntegration/Views/Blockchain/AddressDetails.cshtml
@{
    ViewData["Title"] = "Address Details";
}

@model Info.Blockchain.API.Models.Address

<div class="text-center">
    <h1 class="display-4">Address Details</h1>
</div>

<div class="container">
    <div class="text-center">
        <h5>Address Details</h5>
    </div>
    <div>
        <ul>
            <li>
                Address: @Model.Hash160
            </li>
            <li>
                Total Received: @Model.TotalReceived.GetBtc()
            </li>
            <li>
                Total Spent: @Model.TotalSent.GetBtc()
            </li>
            <li>
                Final Balance: @Model.FinalBalance.GetBtc()
            </li>
            <li>
                Total Transactions: @Model.TransactionCount
            </li>
        </ul>
    </div>
</div>

PaymentGatewayIntegration/Views/Blockchain/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model BlockchainModel;
<div class="text-center">
    <h1 class="display-4">Pay using Blockchain</h1>
</div>

<div class="container">
    <div class="card">
        <div class="card-header">Payment Details</div>
        <div class="card-body">
            @using (Html.BeginForm("ProcessPayment", "Blockchain", FormMethod.Post, new { @class = "row" }))
            {
                @Html.HiddenFor(x => x.MarketPriceUsd)
            <div class="col-md-6">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                @if (@ViewBag.Message != null)
                {
                    <div style="border: 1px solid red">
                        @ViewBag.Message
                    </div>
                }
                <div class="form-group">
                    @Html.LabelFor(a => a.FirstName)
                    @Html.TextBoxFor(a => a.FirstName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(a => a.FirstName)
                </div>
                <div class="form-group">
                    @Html.LabelFor(a => a.LastName)
                    @Html.TextBoxFor(a => a.LastName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(a => a.LastName)
                </div>
                <div class="form-group">
                    @Html.LabelFor(a => a.Email)
                    @Html.TextBoxFor(a => a.Email, new { @class = "form-control" })
                    @Html.ValidationMessageFor(a => a.Email)
                </div>
                <div class="form-group">
                    @Html.LabelFor(a => a.Amount)
                    @Html.TextBoxFor(a => a.Amount, new { @class = "form-control" })
                    @Html.ValidationMessageFor(a => a.Amount)
                </div>
                <div class="form-group">
                    @Html.LabelFor(a => a.AmountInBTC)
                    @Html.TextBoxFor(a => a.AmountInBTC, new { @class = "form-control", @readonly = "readonly" })
                </div>
                <button type="submit" class="btn btn-primary">Pay</button>
            </div>

            }
        </div>
    </div>
</div>
@section Scripts{ 
    <script type="text/javascript">
        $('#Amount').change(function () {
            var amount = $('#Amount').val();
            var marketPriceUsd = $('#MarketPriceUsd').val();
            var value = amount / marketPriceUsd;
            $('#AmountInBTC').val(value.toFixed(4));
        });
    </script>
}

PaymentGatewayIntegration/Views/Blockchain/ProcessPayment.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model Info.Blockchain.API.Models.ReceivePaymentResponse

<div class="text-center">
    <h1 class="display-4">Pay using Blockchain</h1>
</div>

<div class="container">
    <div class="text-center">
        <h5>Payto this Address</h5>
        <h4>
            @Model.Address <a href="/blockchain/AddressDetails/@Model.Address" target="_blank"> Get Address Details</a>
        </h4>
        <img src="http://chart.googleapis.com/chart?chs=125x125&cht=qr&chl=@Model.Address" width="50%" class="border">
    </div>
</div>

PaymentGatewayIntegration/Views/Blockchain/Success.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}