PaymentGatewayIntegration/Controllers/PayPalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PaymentGatewayIntegration.Models;
using PaymentGatewayIntegration.Services;
using PayPalCheckoutSdk.Orders;

namespace PaymentGatewayIntegration.Controllers
{
    public class PayPalController : Controller
    {
        private readonly IPaypalService _paypalService;
        public PayPalController(IPaypalService paypalService)
        {
            _paypalService = paypalService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> ProcessPayment(PaypalModel model)
        {
            var order = await _paypalService.ProccessPayment(model);
            var redirectUrl = string.Empty;
            if (order != null)
            {
                HttpContext.Session.SetString("PaypalOrderId", order.Id);
                foreach (var linkDescription in order.Links)
                {
                    if ("approve".Equals(linkDescription.Rel))
                    {
                        redirectUrl = linkDescription.Href;
                    }
                }
            }
            if (!string.IsNullOrEmpty(redirectUrl))
            {
                return Redirect(redirectUrl);
            }
            return View();
        }

        public async Task<IActionResult> Return()
        {
            string payerId = Request.Query["PayerID"];
            string token = Request.Query["Token"];
            string orderId = HttpContext.Session.GetString("PaypalOrderId");
            var response = await _paypalService.ProccessPaymentApproval(orderId);
            if (response != null)
            {
                return View("Success", response);
            }
            return View("Failed");
        }
    }
}

PaymentGatewayIntegration/Views/PayPal/Failed.cshtml
@{
    ViewData["Title"] = "Paypal Failed Page";
}

<div class="text-center">
    <h1 class="display-4">Your last transaction was not completed or Failed !!!</h1>
</div>

PaymentGatewayIntegration/Views/PayPal/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Pay using Skrill</h1>
</div>

@model PaypalModel

<div class="container">
    <div class="card">
        <div class="card-header">Payment Details</div>
        <div class="card-body">
            @using (Html.BeginForm("ProcessPayment", "PayPal", FormMethod.Post, new { @class = "row" }))
            {
                <div class="col-md-6">
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    @if (@ViewBag.Message != null)
                    {
                        <div style="border: 1px solid red">
                            @ViewBag.Message
                        </div>
                    }
                    <div class="form-group">
                        @Html.LabelFor(a => a.FirstName)
                        @Html.TextBoxFor(a => a.FirstName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(a => a.FirstName)
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(a => a.LastName)
                        @Html.TextBoxFor(a => a.LastName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(a => a.LastName)
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(a => a.Email)
                        @Html.TextBoxFor(a => a.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(a => a.Email)
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(a => a.Amount)
                        @Html.TextBoxFor(a => a.Amount, new { @class = "form-control" })
                        @Html.ValidationMessageFor(a => a.Amount)
                    </div>
                    <button type="submit" class="btn btn-primary">Pay</button>
                </div>
            }
        </div>
    </div>
</div>

PaymentGatewayIntegration/Views/PayPal/Status.cshtml
<p>Payment from Skrill</p>

PaymentGatewayIntegration/Views/PayPal/Success.cshtml
@{
    ViewData["Title"] = "Paypal Success Page";
}

@model PayPalCheckoutSdk.Orders.Order

@if (Model != null)
{
    <div class="text-center">
        <h1 class="display-4">Your last transaction was completed!!!</h1>
    </div>
    <div class="text-center">
        <label>Paypal Order Id</label> : @Model.Id <br />
        @*<label>Paypal Invoice Id</label> : @Model.PurchaseUnits[0].InvoiceId <br />*@
        <label>Amount</label> : @Model.PurchaseUnits[0].AmountWithBreakdown.Value  @Model.PurchaseUnits[0].AmountWithBreakdown.CurrencyCode <br />
    </div>
}
else
{
    <div class="text-center">
        <h1 class="display-4">Your last transaction was not completed or Failed !!!</h1>
    </div>
}